### ISSUE TITLE
dumpall\addons\dsdumper.py  第26行少写一个*   导致.DS_Store类型  跑不起来

### ISSUE THREAD

**Issue by not-know** [0xHJK/dumpall#18]
原文
super(Dumper, self).__init__(url, outdir, *kwargs)

改成这样就跑起来了
super(Dumper, self).__init__(url, outdir, **kwargs)

**Comment by not-know** [comment]
('__init__() takes 3 positional arguments but 6 were given',)

**Comment by 0xHJK** [comment]
已修改 谢谢
